[package]
name = "rust-packet"
version = "0.1.0"
authors = ["Emmanuel Thompson <eet6646@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
hashbrown = "0.11"
deku = { version = "0.12", default-features = false, features = ["alloc"] }

[dev-dependencies]
rstest = "0.10.0"
hexlit = "0.5.0"
